services:
  - type: web
    name: account-vault
    runtime: python
    plan: free
    buildCommand: >
      pip install -r backend/requirements.txt &&
      cd frontend && npm ci && npm run build &&
      mkdir -p ../backend/static &&
      cp -r dist/* ../backend/static/
    startCommand: bash backend/start.sh
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: GOOGLE_CREDENTIALS_JSON
        sync: false
      - key: GOOGLE_SHEETS_NAME
        value: Accounts
